name: my_todo_app
description: My To-Do App
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5
  flutter_slidable: ^4.0.3
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

# === ADD THESE TWO SECTIONS AT THE BOTTOM ===

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#6C63FF"
  image: assets/splash.png
  android: true
  ios: true
  branding: assets/icon.png